// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package depend_inject

// Injectors from injector.go:

// run command: `wire gen open_api/depend_inject`
// or run command `cd depend_inject && wire`
func InitializeService() *SimpleService {
	simpleRepository := NewSimpleRepository()
	simpleService := NewSimpleService(simpleRepository)
	return simpleService
}
